### ISSUE TITLE
Closing requests' bodies after decoding JSON

### ISSUE THREAD

**Issue by silktrader** [sapienzaapps/wasa-fountains#1]
Consider this [statement](https://github.com/sapienzaapps/wasa-fountains/blob/69fc5b66ac56e46cd6a3774e24d75d36a76d1419/service/api/create-fountain.go#L14):

```go
func (rt *_router) createFountain(w http.ResponseWriter, r *http.Request, ps httprouter.Params, ctx reqcontext.RequestContext) {
	// Read the new content for the fountain from the request body.
	var fountain Fountain
	err := json.NewDecoder(r.Body).Decode(&fountain)
	_ = r.Body.Close()
	...
}
```

```Body``` is a ```ReadCloser```, which requires the implementation of ```Close()```, by way of ```Closer```.
The concern is that without the explicit ```Close()``` call, resources won't be freed and the connection won't be reused within short.

When unmarshalling JSON, some (reputable) authors omit this statement (and its deferred alternative), others include it.
The official [code base](https://go.dev/src/net/http/request.go#L165), on this matter, reports:

>  For server requests, the Request Body is always non-nil
 but will return EOF immediately when no body is present.
The Server will close the request body. The ServeHTTP
Handler does not need to.

You can follow the link for the paragraph's context.

On first reading that comment, I would conclude that ```Close()``` calls are unnecessary in this scenario. I wonder whether the wise, but obscure, Golang folks don't refer to bodies that weren't ```read()``` at all.

```JSONDecoder``` will happily ingest JSON tokens, but does it exhaust the stream? I found out that a call to ```decode()``` will only process the first token, in a request such as: ```{}{}{"UserId":"c09cb1fd-495f-4f63-84dc-87c15a2f7740"}```, silently ignoring the last token.

These ```request.Body.Close()``` can't hurt as they are equivalent to NOPs, but are they required?

**Comment by Enrico204** [comment]
As stated by the official doc, these statements are not required in ServeHTTP handlers. In fact, [the `io.Closer` interface documentation](https://pkg.go.dev/io#Closer) says that:

> The behavior of Close after the first call is undefined

Given the comment you just quoted from the doc, this is indeed a bug in the project. I'll fix it ASAP. Thanks!

Note that the same [is not valid for `http.Client`](https://pkg.go.dev/net/http). Since client and server structures are the same, I developed a good habit of closing the body in clients (which is a good thing). In this case, it seems that I swapped the server and the client.

Regarding the JSON decoder, [the doc for `encoding/json` NewDecoder](https://pkg.go.dev/encoding/json#NewDecoder) says that the JSON decoder may read more bytes, ingesting (and throwing away, probably) garbage at the end of the stream:

> The decoder introduces its own buffering and may read data from r beyond the JSON values requested.

However, note that the decoder can read multiple JSON in a stream. The format you used as an example is "streamed JSON" or "streaming JSON", and it's supported by Go:

```go
package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

const js = `{}{}{"UserId":"c09cb1fd-495f-4f63-84dc-87c15a2f7740"}`

func main() {
	strbuf := strings.NewReader(js)
	jdec := json.NewDecoder(strbuf)

	var tmp struct {
		UserId string
	}

	err := jdec.Decode(&tmp)
	fmt.Println(err)
	fmt.Println(tmp)

	err = jdec.Decode(&tmp)
	fmt.Println(err)
	fmt.Println(tmp)

	err = jdec.Decode(&tmp)
	fmt.Println(err)
	fmt.Println(tmp)
}
```

([here the link for Go Playground](https://go.dev/play/p/Wot5l-URhHi))

While this is a valid "protocol" to send multiple JSON in a stream, it's not expected in REST APIs. You can use it in WebSocket, for example.
